export class AddVehicleConstants {
  public static outsideColor: Array<string> = [
    'White',
    'Silver',
    'Grey',
    'Black',
    'Blue',
    'Red',
    'Green',
    'Orange',
    'Brown',
    'Gold',
    'Beige',
    'Purple',
    'Pink',
    'Yellow'
  ];
  public static fuelTypeList: Array<string> = ['Diesel', 'Gasoline', 'Electric', 'Hybrid'];
  public static glassTypeList: Array<string> = ['Manuals', 'Electrical', 'Front Electric'];
  public static comfortList: Array<string> = [
    'Air conditioning (climate control)',
    'Door armrests',
    'Detachable front and rear headrests',
    'Folding and reclining rear bench seat',
    "Electric driver's seat",
    'Heater',
    'Remote ignition control',
    'Upholstered leather seats',
    'Adjustable steering wheel',
    'Electric front seats',
    'Third Row of Seats',
    'Changes At The Wheel',
    'Radio Control on The Steering Wheel',
    'Electric Seats',
    'Cruise Speed',
    'Sports Steering Wheel',
    'A/C Seats'
  ];
  public static technologyList: Array<string> = [
    'Adaptive Cruise Control',
    'Blind Spot Alert (BSA)',
    'Parking Assist',
    'Tire Pressure Monitoring System (TPMS)',
    'Stability Control System',
    'Rear Cross Traffic Alert System',
    'Satelite Device',
    'GPS',
    'Sliding Roof',
    'Rain Sensors',
    'Rear Parking Sensors',
    'Light Sensors',
    'Reverse Camera',
    'Wash Headlights',
    'Electic Collapsible Outside Mirrors',
    'Front Parking Sensor',
    'Panoramic Roof',
    'Electric Gate',
    'Push-button Ignition',
    'Front Screen',
    '360° Camera',
    //'Manual Glasses',
  ];
  public static entertainmentList: Array<string> = [
    'Bluetooth',
    'Premium Sound System',
    'Wireless Device Charging',
    'Rear Seat Displays',
    'Voice Recognition System',
    'GPS Navigation System',
    'Ambient Lights',
    'Apple CarPlay',
    'MP3 Radio',
    'DVD Player',
    'CD Radio',
    'Android Auto',
    'Speakers/Bass',
  ];
  // public static utilityList: Array<string> = [
  //     'Hoops',
  //     'Wreking Ball',
  //     'Winch/Crane',
  //     '16 Valve',
  //     '20 valves',
  //     '32 valves',
  //     '24 valves',
  //     'Twin Turbo',
  //     'Special Tires',
  //     'Turbo',
  //     'Zumbaburros/Mataburros',
  //     'Led Lights',
  //     'Aileron',
  //     'Xenon Lights',
  //     'Grill',
  //     'Drum',
  //     'Stirrups',
  //   ];
  public static securityList: Array<string> = [
    'Driver and passenger front air bags',
    'Driver and Passenger Side Seat Air Bags',
    'Roof side air bags',
    'ISOFIX anchorages (3 points) child seats (2)',
    'Anti-impact side bars',
    'Rear axle differential lock (4x4 versions)',
    'Retractable front seat belts',
    'Reverse camera',
    'Lift and descent control',
    'Front and rear ventilated disc brakes',
    'Parking sensors (front and rear)',
    'Front collision sensor',
    'ABS and EBD braking system on all 4 wheels',
    'Electronic Stability Control',
    'Side crossing sensor (outside rearview mirrors)',
    'Alarm',
    'Fog Lights',
    'Automatic Locks',
    'Center Lock',
    'Security Sheets',
    //'ABS Brakes',
    //'Airbag',
  ];
  public static tonCapacityList: Array<string> = [
    '0 to 3 Ton',
    '3.5 Ton',
    '3.6 Ton',
    '5 Ton',
    '6 Ton',
    '8 Ton',
    '9 Ton',
    '10 Ton',
    '12 Ton',
    '13 Ton',
    '13.5 Ton',
    '18 Ton',
    '19.5 Ton',
    '20 Ton',
    '22 Ton',
    '28 Ton',
    '42 Ton',
    '45 Ton',
    '48 Ton',
    '8M3',
    '12M3',
  ];
  public static mileageList: Array<string> = ['Kilometers', 'Miles', 'Hours'];
  public static transmissionList: Array<string> = ['Manual',
  'Automatic',
  'Secuence',
  'Continuously variable',
  'Double clutch',
  'Geared',
  'Hydrostatic / Continuous'
  ];
}

export enum VehicleTypes {
  WorkMachinery = 'Work Machinery',
  Automobiles = 'Automobiles',
  Heavy = 'Heavy',
  Buses = 'Buses'
}
